# Generated by Django 2.2.5 on 2020-08-31 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='users',
            field=models.ManyToManyField(related_name='retruits', to=settings.AUTH_USER_MODEL, verbose_name='收藏者'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='users',
            field=models.ManyToManyField(related_name='enterpises', to=settings.AUTH_USER_MODEL, verbose_name='收藏者'),
        ),
    ]
